backend:
  name: git-gateway
  branch: main

media_folder: "/images"
public_folder: "/images"

collections:
  - name: "pages_en"
    label: "Pages (EN)"
    folder: "astro/src/pages/en"
    create: true
    slug: "{{title}}"

    nested:
      depth: 100
      summary: "{{title}}"
      subfolders: true

    meta:
      path:
        widget: string
        label: "Path"
        index_file: "index"

    fields: &pageFields
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "/src/layouts/MDLayout.astro"

      - label: "Language"
        name: "lang"
        widget: "hidden"
        default: "en"

      - label: "Title"
        name: "title"
        widget: "string"

      # for proper URL generation, we need a separate slug field that doesn't allow uppercase letters or accents
      # - label: "Slug"
      #   name: "slug"
      #   widget: "string"
      #   slug: "{{slug}}"
      #   preview_path: "{{slug}}"
      #   required: true
      #   hint: "Auto-generated from title. Use lowercase, no accents."
      #   pattern:
      #     [
      #       "^[a-z0-9-/]+$",
      #       "Only lowercase letters, numbers, dashes and / allowed",
      #     ]

      - label: "Featured image"
        name: "featuredImage"
        widget: "image"
        required: false

      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field:
          label: "Image"
          name: "image"
          widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
        modes: ["rich_text"]
        required: false

  - name: "pages_lv"
    label: "Pages (LV)"
    folder: "astro/src/pages/lv"
    create: true
    slug: "{{title}}"

    nested:
      depth: 100
      summary: "{{title}}"
      subfolders: true

    meta:
      path:
        widget: string
        label: "Path"
        index_file: "index"

    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "/src/layouts/MDLayout.astro"

      - label: "Language"
        name: "lang"
        widget: "hidden"
        default: "lv"

      - label: "Title"
        name: "title"
        widget: "string"

      # for proper URL generation, we need a separate slug field that doesn't allow uppercase letters or accents
      # - label: "Slug"
      #   name: "slug"
      #   widget: "string"
      #   slug: "{{slug}}"
      #   preview_path: "{{slug}}"
      #   required: true
      #   hint: "Auto-generated from title. Use lowercase, no accents."
      #   pattern:
      #     [
      #       "^[a-z0-9-/]+$",
      #       "Only lowercase letters, numbers, dashes and / allowed",
      #     ]

      - label: "Featured image"
        name: "featuredImage"
        widget: "image"
        required: false

      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field:
          label: "Image"
          name: "image"
          widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
        modes: ["rich_text"]
        required: false
