backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "pages_en"
    label: "Pages (EN)"
    folder: "src/pages/en"
    create: true
    slug: "{{slug}}"

    nested:
      depth: 100
      summary: "{{title}}"
      subfolders: true

    meta:
      path:
        widget: string
        label: "Path"
        index_file: "index"

    fields: &pageFields
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "/src/layouts/MDLayout.astro"

      - label: "Language"
        name: "lang"
        widget: "hidden"
        default: "en"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Featured image"
        name: "featuredImage"
        widget: "image"
        required: false

      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field:
          label: "Image"
          name: "image"
          widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
        modes: ["rich_text"]
        required: false

  - name: "pages_lv"
    label: "Pages (LV)"
    folder: "src/pages/lv"
    create: true
    slug: "{{slug}}"

    nested:
      depth: 100
      summary: "{{title}}"
      subfolders: true

    meta:
      path:
        widget: string
        label: "Path"
        index_file: "index"

    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "/src/layouts/MDLayout.astro"

      - label: "Language"
        name: "lang"
        widget: "hidden"
        default: "lv"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Featured image"
        name: "featuredImage"
        widget: "image"
        required: false

      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field:
          label: "Image"
          name: "image"
          widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
        modes: ["rich_text"]
        required: false
