backend:
  name: git-gateway
  branch: main

media_folder: "astro/src/assets/images"
public_folder: "astro/src/assets/images"

collections:
  - name: "text_en"
    label: "Text (EN)"
    folder: "astro/src/pages/text/en"
    create: true
    slug: "{{slug}}"
    fields: &textFields
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Cover image",
          name: "cover",
          widget: "image",
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          modes: ["rich_text"],
        }

  - name: "text_lv"
    label: "Text (LV)"
    folder: "astro/src/pages/text/lv"
    create: true
    slug: "{{slug}}"
    fields: *textFields

  - name: "books_en"
    label: "Books (EN)"
    folder: "astro/src/pages/books/en"
    create: true
    slug: "{{slug}}"
    fields: &bookFields
      - { label: "Title", name: "title", widget: "string" }
      # - { label: "Year", name: "year", widget: "string" }
      - {
          label: "Featured image",
          name: "featuredImage",
          widget: "image",
          required: false,
        }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          modes: ["rich_text"],
        }

  - name: "books_lv"
    label: "Books (LV)"
    folder: "astro/src/pages/books/lv"
    create: true
    slug: "{{slug}}"
    fields: *bookFields

  - name: "other_en"
    label: "Other (EN)"
    folder: "astro/src/pages/other/en"
    create: true
    slug: "{{slug}}"
    fields: &otherFields
      - { label: "Title", name: "title", widget: "string" }
      # - { label: "Year", name: "year", widget: "string" }
      - {
          label: "Featured image",
          name: "featuredImage",
          widget: "image",
          required: false,
        }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          modes: ["rich_text"],
        }

  - name: "other_lv"
    label: "Other (LV)"
    folder: "astro/src/pages/other/lv"
    create: true
    slug: "{{slug}}"
    fields: *otherFields

  - name: "about_en"
    label: "About (EN)"
    folder: "astro/src/pages/about/en"
    create: true
    slug: "{{slug}}"
    fields: &aboutFields
      - { label: "Title", name: "title", widget: "string" }
      # - { label: "Year", name: "year", widget: "string" }
      - {
          label: "Featured image",
          name: "featuredImage",
          widget: "image",
          required: false,
        }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          modes: ["rich_text"],
        }

  - name: "about_lv"
    label: "About (LV)"
    folder: "astro/src/pages/about/lv"
    create: true
    slug: "{{slug}}"
    fields: *aboutFields
